### ISSUE TITLE
rnpm

### ISSUE THREAD

**Issue by casperin** [oblador/react-native-keychain#15]
I'm very new to anything apps and xcode, but I just tried to install this plugin and link it up using `rnpm link`. It didn't link up properly (I think it linked up with the examples maybe?) so I ended up having to do it manually.

Not a huge issue, but I imagine it's quite easy to integrate properly :)

**Comment by oblador** [comment]
cc @kureev & @grabbou

**Comment by Kureev** [comment]
Hi @casperin! Can you give us more info about what went wrong with `rnpm`, please?

**Comment by casperin** [comment]
I think it linked up the examples actually.

**Comment by grabbou** [comment]
Ah @oblador if you don't mind renaming the example folder to be `Examples` - that would be cool (we only exclude by full folder name as in this constant https://github.com/rnpm/rnpm/blob/master/src/config/ios/findProject.js#L11).

Otherwise, if you could set:
```js
{
  "rnpm": {
     "ios": {
         "project": "./relative-path-to-xcodeproj"
    }
  }
}
```
it would be cool!

CC: @casperin you can try adding the above `json` to keychain `package.json` in your node_modules to see if it works.

**Comment by Kureev** [comment]
Thanks @grabbou, just wanted to write the same comment :smile:

**Comment by oblador** [comment]
Actually the example shouldn't even be in the package from npm :-)

**Comment by oblador** [comment]
Should be fixed in 0.2.7!

**Comment by Kureev** [comment]
:+1:

**Comment by grabbou** [comment]
Just to let you know, this has been fixed in rnpm master and will land soon in npm - now we skip any folder that either contains `test` or `example` in it.

**Comment by casperin** [comment]
I can confirm that it works. Thanks guys! :beers:
