### ISSUE TITLE
Can updated IOS versions break keychain implementation?

### ISSUE THREAD

**Issue by mdere-unbound** [oblador/react-native-keychain#222]
So something I noticed, I was testing on 12.2 iOS and I was able to write to authenticate in - but as soon I upgraded to 12.3.1 things aren't working - I haven't fully investigated yet, but my question is `Can updated IOS versions break keychain implementation?`

**Comment by vonovak** [comment]
hello and thanks for reporting!

> Can updated IOS versions break keychain implementation?

There probably isn't a person in the world who can answer such question with 100% certainty. To answer the question - why don't you try? It seems you perhaps already did it, why not share a demo with repro steps?

**Comment by genuinezack** [comment]
Coming from the world of iOS full-native development, I will echo @vonovak's comment that much of Apple's legacy code, *especially* Keychain-related, is shrouded in mystery and misery. The main things to watch out for from the perspective of the native-level are:
1. Is the system fully unlocked? When the phone is in a state where the user has to enter their passcode to continue (after first boot, after OS upgrade, or after a security or emergency lockout), then keychain items with an accessibility of `Keychain.ACCESSIBLE.WHEN_UNLOCKED` will be inaccessible.
2. Was the upgrade a smooth "in place" upgrade, or was the device reset, upgraded, and then restored from iCloud or on-disk backup. (The latter is what happens when you install or revert a beta, when you DFU upgrade, or in certain rare other cases.) If the app was deleted and then restored from iCloud, only passwords that were marked with any of the `THIS_DEVICE_ONLY` accessibility values will have been removed.

Hopefully those two gotchas (both of which have really ruined my day in production before) will help you in your investigation into where your keychain values have gone @mdere-unbound.
