### ISSUE TITLE
App hangs on OnePlus 6T and above!!

### ISSUE THREAD

**Issue by Raythode** [oblador/react-native-keychain#335]
Hello,
I have recently used this package to implement biometric authentication in my react-native app. It works perfectly, but I am facing an issue in OnePlus 6T and above devices.

Below are the listed issues that i am facing.
1.  Biometrics works perfectly if i authenticate successfully. But if i authenticate with wrong finger, the prompt goes away and my app hangs. I have to restart the app to make it working again.
2. I cannot cancel the biometrics prompt, as i only see a fingerprint icon on the phone. No cancel button like other android devices to cancel it.

To be honest i am just a react-native developer and not a native android or IOS developer (I am currently learning to become a native developer). So i have less clue of what's wrong. But i did my research and found this https://forums.oneplus.com/threads/problems-about-oneplus-6t-fingerprint-api.944959/. I would try to fix this on my own but it would take me ages. Please help.

**Comment by MichalCiesliczka** [comment]
One of the solution I've made implemented (on my old fork of this repo, not really along with current one since 7th of November 2019) is to replace `setNegativeButtonText` found [here](https://github.com/oblador/react-native-keychain/blob/master/android/src/main/java/com/oblador/keychain/KeychainModule.java#L559) with `setDeviceCredentialAllowed` option.

What this cause?
- On all devices I've tested (OnePlus 6T, Samsung S10e, Xiaomi 5a) it will not display an on screen prompt, but will popup with separated screen.
- You won't have `Cancel` button, but you can still click on go back arrow on the bottom
- After 5th failure you'll be asked for a PIN/Password/Pattern whateva

As I said - I've tested it on my fork, not sure if it'll work here, but I cannot see a reason why not. However it'll change a little bit UI and UX of your app

**Comment by Raythode** [comment]
> setDeviceCredentialAllowed

Will Try it out and see if that fixes my problem.

**Comment by sgal** [comment]
#447 Fixes this issue as well.
