### ISSUE TITLE
Different responses from getGenericPassword before/after reload

### ISSUE THREAD

**Issue by jpaas** [oblador/react-native-keychain#70]
Using 1.2.0 with RN 0.44.2 on iOS...

I am using `setGenericPassword`, `getGenericPassword` and `resetGenericPassword` for storing some credentials.

When the user signs out I `resetGenericPassword`. Once I have done this I get an inconsistent result when calling `getGenericPassword`. When the app re-launches I receive:

```json
{
  username : null,
  password: "1",
  service: "xxx"
}
```

Note the password of "1". Weird!

But if I reload the JS bundle I get the expected result of `false`.

Another thing I noticed is that in the scenario where I get the weird JSON response, it always seems to generate this error when I call getGenericPassword:

```
RCTJSONStringify() encountered the following error: Invalid type in JSON write (__NSCFData)
reactConsoleErrorHandler @ ExceptionsManager.js:71
console.error @ YellowBox.js:62
logToConsole @ RCTLog.js:45
logIfNoNativeHook @ RCTLog.js:31
__callFunction @ MessageQueue.js:250
(anonymous) @ MessageQueue.js:101
__guard @ MessageQueue.js:218
callFunctionReturnFlushedQueue @ MessageQueue.js:100
addEventListener @ RNDebuggerWorker.js:1
```

Android seems to consistently return `false`

**Comment by schultka** [comment]
Same here. Android works like expected. iOS returns `{username: null, password: "1"}` whenever I call `resetGenericPassword`.

**Comment by levsero** [comment]
Having the same issue, though it only happens on the initial install, if I reset it does not happen again. Still confirming but it appears our issue started after adding the firebase sdk (with https://github.com/evollu/react-native-fcm).

**Comment by vonovak** [comment]
That's an interesting observation, in fact, just today I also saw a
Keychain-related error (which I have not seen before) on my device and I
have integrated the fcm package just yesterday!

On Feb 16, 2018 5:07 PM, "Levi Serebryanski" <notifications@github.com>
wrote:

Having the same issue, though it only happens on the initial install, if I
reset it does not happen again. Still confirming but it appears our issue
started after adding the firebase sdk (with https://github.com/evollu/
react-native-fcm).

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/oblador/react-native-keychain/issues/70#issuecomment-366278805>,
or mute the thread

**Comment by oblador** [comment]
That's very odd, can you try specifying service and see if the issue persists?

**Comment by DevChuckNorris** [comment]
Also happens for me when specifying a custom service.

**Comment by 404sand808s** [comment]
I also get it with a specified service.

**Comment by nhnam** [comment]
Make sure you getGenericPassword with the same key with when you set it
`Keychain.setGenericPassword('<serviceKey>','<serviceValue>');`
 --> `Keychain.getGenericPassword('<**serviceKey**>');`

**Comment by krzysztofnowak** [comment]
Issue still exists in v3.1.3

After resetGenericPassword()

getGenericPassword() returns
Object {service: "my.package.name", username: null, password: "1"}

**Comment by doruxan** [comment]
My app also stated to behave that way recently

**Comment by voxspox** [comment]
any news on this?

**Comment by vonovak** [comment]
hello folks, this issue is pretty old, it's not clear with what version this happens with and there are no steps to reproduce.

If you're experiencing the issue, try to create a runnable reproduction of it or if the issue is device dependent or is hard to reproduce in some other way, please consider contributing a fix for it yourself. thanks!
